-- Monthly progress reports (Premium-only feature)
-- Generated by monthly cron job, displayed on /reports page.

CREATE TABLE IF NOT EXISTS ea_monthly_reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  month TEXT NOT NULL, -- Format: 'YYYY-MM', e.g. '2026-04'
  report_data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, month)
);

CREATE INDEX IF NOT EXISTS ea_monthly_reports_user_month_idx
  ON ea_monthly_reports(user_id, month DESC);
